// Generated by CoffeeScript 1.6.3
(function() {
  describe('Testing markdown block elements', function() {
    var run_parser, shim;
    shim = {
      blocks: [],
      index: 0
    };
    shim.can_be_nested = markdown.can_be_nested;
    shim.is_whitespace = markdown.is_whitespace;
    run_parser = function(parser) {
      return markdown.parsers[parser].call(shim);
    };
    it('headings', function() {
      var result;
      shim.blocks[0] = '## Heading';
      result = run_parser('atxheading');
      expect(result.type).toBe('h2');
      shim.blocks[0] = '# Heading';
      result = run_parser('atxheading');
      expect(result.type).toBe('h1');
      shim.blocks[0] = '####### Heading';
      result = run_parser('atxheading');
      return expect(result.type).toBe('h6');
    });
    it('unordered lists', function() {
      var result;
      shim.blocks[0] = '- Hello';
      result = run_parser('ulist');
      expect(result.type).toBe('ul');
      shim.blocks[0] = '* Hello';
      result = run_parser('ulist');
      return expect(result.type).toBe('ul');
    });
    it('ordered lists', function() {
      var result;
      shim.blocks[0] = '1. Hello';
      result = run_parser('olist');
      return expect(result.type).toBe('ol');
    });
    it('nested lists', function() {
      var result;
      shim.can_be_nested = function() {
        return true;
      };
      shim.blocks[0] = '  2. hej';
      result = run_parser('olist');
      expect(result.type).toBe('ol');
      shim.blocks[0] = '  - hej';
      result = run_parser('ulist');
      expect(result.type).toBe('ul');
      shim.can_be_nested = function() {
        return false;
      };
      shim.blocks[0] = '  2. hej';
      result = run_parser('olist');
      expect(result).toBe(false);
      shim.blocks[0] = '  - hej';
      result = run_parser('ulist');
      return expect(result).toBe(false);
    });
    return it('quotes', function() {
      var result;
      shim.blocks[0] = '> bananas';
      result = run_parser('quote');
      expect(result.type).toBe('quote');
      shim.blocks[0] = '>bananas';
      result = run_parser('quote');
      return expect(result).toBe(false);
    });
  });

}).call(this);
